### ISSUE TITLE
php svm

### ISSUE THREAD

**Issue by evheniy** [camspiers/statistical-classifier#23]
Hi
Could you please write example like http://php.net/manual/ru/svm.examples.php (migrate from php svm to your lib)
I didn't understand how I can use arrays for addDocument.
Thank you

**Comment by camspiers** [comment]
This library is primarily for text classification, and the SVM version will build the correct svm format for the input you provide.

Hope this helps:

https://github.com/camspiers/statistical-classifier/blob/master/examples/basic_svm.php
https://github.com/camspiers/statistical-classifier/blob/master/examples/svm.php

**Comment by evheniy** [comment]
Thank you
