### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by nimasdj** [camspiers/statistical-classifier#27]
I don't know the difference of bayes abd svm? To detect spams which one shoul I go with?

``` php
use Camspiers\StatisticalClassifier\Classifier\ComplementNaiveBayes;
use Camspiers\StatisticalClassifier\DataSource\DataArray;

$source = new DataArray();
$source->addDocument('spam', 'Some spam document');
$source->addDocument('spam', 'Another spam document');
$source->addDocument('ham', 'Some ham document');
$source->addDocument('ham', 'Another ham document');

$classifier = new ComplementNaiveBayes($source);
$classifier->is('ham', 'Some ham document'); // bool(true)
$classifier->classify('Some ham document'); // string "ham"
```

For addDocument, first param is a name and second param is fir example email source we want to look into? The what exactly shoukd be first and second param of is() and classify()?

**Comment by nimasdj** [comment]
I looked at source code, is it a correct usage?

``` php
$source = new DataArray();
$source->addDocument('spam', 'viagra');
$source->addDocument('spam', 'cancer');
$classifier = new ComplementNaiveBayes($source);
$classifier->is('spam', $email_text); 
```

If yes, is it case sensitive for Viagra and Viagra? and what is difference of SVM and Bayes?

**Comment by camspiers** [comment]
SVM requires a PHP extension to use. It might perform better, but CNB is pretty performant.

Casing is handled by document normalizers, and by default both SVM and Naive Bayes use the Lowercase normalizer. This means that documents are case insensitive by default, but you can change this by implementing your own document normalizer.

The first parameter of `addDocument` is the category of the text, and the second argument is the text/document. so `addDocument('spam', 'some spammy content')` and `addDocument('ham', 'some regular non-spammy content')`.

Data source API:

https://github.com/camspiers/statistical-classifier/blob/master/src/Camspiers/StatisticalClassifier/DataSource/DataSourceInterface.php#L47-L52

The default normalizer:

https://github.com/camspiers/statistical-classifier/blob/master/src/Camspiers/StatisticalClassifier/Classifier/ComplementNaiveBayes.php#L64

The implementation of a normalizer:

https://github.com/camspiers/statistical-classifier/blob/master/src/Camspiers/StatisticalClassifier/Normalizer/Document/Lowercase.php

**Comment by zawaruddin** [comment]
The process in SVM
read document > normalize document > tokenization > stopword > stemming > processing in SVM (use TFIDF and SVM) right?

how to display each data per document after SVM process?
thank you
