### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by nimasdj** [camspiers/statistical-classifier#28]
``` php
$email_text = "Hello, how are you?";
$source = new DataArray();
$source->addDocument('spam', 'viagra');
$source->addDocument('spam', 'cancer');
//$source->addDocument('ok', 'how');
$classifier = new ComplementNaiveBayes($source);

if($classifier->is('spam', $email_text)) {
   print("<br>Yes<br>");
}
print($classifier->classify($email_text));
```

It classifies $email_text as spam and the if clause is true, unless otherwise I uncomment 'ok' category, so should I add a category for each and every words if they are not spam?

**Comment by camspiers** [comment]
You are only going to get reliable results by training the data model/classifier with more documents both spam and not spam. The way you typically use a classifier is to have a corpus (many documents) of spam (preferably spam you have already received so it is representative), and a corpus (many documents) of non-spam (preferably non-spam that you have already received so it is representative).

Training the classifier with such representative documents will make it more accurate.

**Comment by nimasdj** [comment]
So for spams, would it be good to use your zipped files? Using files on zip will give me accurate result?

**Comment by camspiers** [comment]
No, for anything you want to classify, you want to use a representative sample of that category of documents. So in your case, if you are classifying spam, I assume you have some examples of spam that you are trying to identify. Use those as your training corpus.

The zipped files in the resources folder are for testing purposes, you should use your own documents to train the classifier. 

If you don't have any data, maybe the following would be useful for you? http://csmining.org/index.php/spam-email-datasets-.html
