### ISSUE TITLE
Class 'SVM' not found

### ISSUE THREAD

**Issue by viciopoli01** [camspiers/statistical-classifier#29]
I'm traing to use svm but the SVM class is not found...

Fatal error: Class 'SVM' not found in /home/ubuntu/workspace/vendor/camspiers/statistical-classifier/src/Camspiers/StatisticalClassifier/Classifier/SVM.php on line 74 Call Stack: 0.0013 243544 1. {main}() /home/ubuntu/workspace/prova.php:0 0.0121 296376 2. Camspiers\StatisticalClassifier\Classifier\SVM->__construct() /home/ubuntu/workspace/prova.php:10

this is the example code code 
`<?php
require_once 'vendor/autoload.php';

use Camspiers\StatisticalClassifier\Classifier\SVM;
use Camspiers\StatisticalClassifier\DataSource\DataArray;

$source = new DataArray();
$source->addDocument('pig', 'Pigs are great. Pink and cute!');
$source->addDocument('wolf', 'Wolves have teeth. They are gray.');
$c = new SVM($source);
$c->setThreshold(0.6);
var_dump($c->classify('0943jf904jf09j34fpj'));`

**Comment by camspiers** [comment]
https://github.com/camspiers/statistical-classifier#svm-support

> For SVM Support both libsvm and php-svm are required. For installation intructions refer to php-svm.

https://github.com/ianbarber/php-svm
