### ISSUE TITLE
Can I use this without composer?

### ISSUE THREAD

**Issue by rizkiyoist** [camspiers/statistical-classifier#30]
My server doesn't allow installing composer. Is there a way for me to maybe copy the library and require them from my code?

**Comment by StasDoskalenko** [comment]
@rizkiyoist hi! Composer just used to download this library and maintain it.
To use without composer just use library as it is https://github.com/camspiers/statistical-classifier#usage

But copy it manually and change namespaces path. That's it!

Eg:

`use \librarypath\src\Camspiers\StatisticalClassifier\Classifier\ComplementNaiveBayes;
use \librarypath\src\Camspiers\StatisticalClassifier\DataSource\DataArray;
`

**Comment by camspiers** [comment]
@rizkiyoist In general you shouldn't need to install composer in your production environment. Composer is a tool to source and download libraries and to specify your projects dependance on them. These steps are generally achieve in the development (and deployment) environment before production.

To source the contents of this library without composer you will need to manually download the code via github. To use the library you will need to use a PSR-4 compliant autoloader, such as the one that composer provides. This will ensure that when you attempt to use the classes provided by the library they will automatically be required/loaded by PHP.

http://www.php-fig.org/psr/psr-4/

Some example autoloaders are here:

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md
