### ISSUE TITLE
Use of namespaces in examples?

### ISSUE THREAD

**Issue by khromov** [camspiers/statistical-classifier#5]
The default examples don't run for me. For example, the Non-cached Naive Bayes example produces:

```
Fatal error: Class 'Classifier\ComplementNaiveBayes' not found in /var/www/html/tmp4711/index.php on line 6
```

This seems to be due to improper use of the "use" keyword.

The PHP docs have the following to say:

``` php
// this is the same as use My\Full\NSname as NSname
use My\Full\NSname;
```

In the examples the following is used:

``` php
use Camspiers\StatisticalClassifier;
$c = new Classifier\ComplementNaiveBayes(
    new Index\Index(
        $source = new DataSource\DataArray()
    )
);
```

But according to the PHP docs, it should be this:

``` php
use Camspiers\StatisticalClassifier;
$c = new StatisticalClassifier\Classifier\ComplementNaiveBayes(
    new StatisticalClassifier\Index\Index(
        $source = new StatisticalClassifier\DataSource\DataArray()
    )
);
```

My proposition is to change all of the examples to the structure below.
It works properly, and maintains legibility of the example.

``` php
use Camspiers\StatisticalClassifier\Classifier;
use Camspiers\StatisticalClassifier\Index;
use Camspiers\StatisticalClassifier\DataSource;

$c = new Classifier\ComplementNaiveBayes(
    new Index\Index(
        $source = new DataSource\DataArray()
    )
);
```

I wanted to throw it out there before making a rather big change to the documentation.

http://php.net/manual/en/language.namespaces.importing.php

**Comment by camspiers** [comment]
Teach me for not testing the examples. This is fixed now

**Comment by camspiers** [comment]
I am happy for you to make that change BTW. I will accept the PR. I just wanted to fix things in the meantime. Thanks again!

**Comment by khromov** [comment]
Sure no problem! I'll submit a PR shortly.

**Comment by khromov** [comment]
PR #6 and #7 submitted!
